FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src 

# Phase #1, copy solution + csproj and restore as distinct layers  ----
COPY . .

RUN dotnet restore 

WORKDIR "/src/Client"

RUN dotnet publish Client.csproj -c Release -o /app/Client --no-restore

# Phase #2, Build final image ------------------------------------------
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS release

COPY --from=build /app/Client .

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "Client.dll"]  
