FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /src 

#copy the files from c:\Project -> container
COPY . .

RUN dotnet restore 

WORKDIR "/src/Client"

RUN dotnet publish Client.csproj -c Release -o /app/Client --no-restore


# Phase #2, Build final image ------------------------------------------
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS release

COPY --from=build /app/Client .

EXPOSE 80

ENTRYPOINT ["dotnet", "Client.dll"]  


