on: [push]
name: Linux_Container_Workflow 

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:

    - name: 'checkout the repo'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: tncontaineregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push to registry'
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile_client
        push: true
        tags: tncontaineregistry.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}


    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: 'ContainerTraining'
        dns-name-label: ${{ secrets.USERNAME }}-client
        image: tncontaineregistry.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}
        registry-login-server: tncontaineregistry.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ secrets.USERNAME }}-client
        ports: 80 443 8080
        cpu: 0.5
        memory: 0.5
        location: 'northeurope'
        environment-variables: ASPNETCORE_ENVIRONMENT=Production