on: [push]
name: Linux_Container_Workflow 

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout the repo'
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
       
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    - name: 'Build and push to registry'
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile_client
        push: true
        tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}
        
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: 'ContainerTraining'
        dns-name-label: ${{ secrets.USERNAME }}-client
        image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ secrets.USERNAME }}-client
        ports: 80 443
        cpu: 0.5
        memory: 0.5
        location: 'northeurope'
        environment-variables: ASPNETCORE_ENVIRONMENT=Production GITHUB__SHA=${{ github.sha }}

        # List files
    - shell: bash
      run: ls

        # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ContainerTraining
        cluster-name: MyAKSCluster1
        admin: 'false'
        use-kubelogin: 'true'

    # Deploys application based on given manifest file
    - name: Deploys application
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        manifests: ./kubernetes
        images: tncontaineregistry.azurecr.io/student1-client:v1 ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}

